swagger: '2.0'
info:
  description: 'This is an API for creating new connectors in the project E-Stream. '
  version: 0.0.1
  title: E-Stream Connector API
  termsOfService: ''
  contact:
    email: pg-e-stream@informatik.uni-oldenburg.de
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: ''
basePath: /api
schemes:
  - http
paths:
  /connector:
    post:
      tags:
        - connector
      summary: Add a new connector
      description: ''
      operationId: addConnector
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Connector configuration
          required: true
          schema:
            $ref: '#/definitions/Connector'
      responses:
        '405':
          description: Invalid input
  '/connector/{connectorName}':
    get:
      tags:
        - connector
      summary: Find Connector by Name
      description: Returns a single connector
      operationId: getConnectorByName
      produces:
        - application/json
      parameters:
        - name: connectorName
          in: path
          description: Name of connector to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Connector'
        '404':
          description: Connector not found
    delete:
      tags:
        - connector
      summary: Delete Connector
      description: ''
      operationId: deleteConnector
      produces:
        - application/json
      parameters:
        - name: connectorName
          in: path
          description: The name of the Connector to be deleted
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '404':
          description: Connector not found
  /model:
    post:
      tags:
        - mining model
      summary: Send a mining model
      description: ''
      operationId: addMiningModel
      consumes:
        - application/xml
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: PMML Data Mining Model
          required: true
          schema:
            $ref: '#/definitions/PMML'
      responses:
        '405':
          description: Invalid input
definitions:
  Connector:
    type: object
    required:
      - sinkUrl
      - connectorType
    properties:
      name:
        type: string
        example: test-connector
      sinkUrl:
        type: string
        description: Address of the data source
        example: 'http://localhost:9000'
      connectorType:
        type: string
        description: Kafka Connector Type
        enum:
          - hdfs
          - jdbc
      connectorProperties:
        type: array
        description: Properties for the data source which will receive the data.
        items:
          type: string
      connectionType:
        description: >-
          This determines whether a connection to the raw data or aggregated
          data is provided
        $ref: '#/definitions/ConnectionType'
      connectorStatus:
        type: string
        enum:
          - UNASSIGNED
          - RUNNING
          - PAUSED
          - FAILED
  PMML:
    type: object
    properties:
      modelConent:
        type: string
  ConnectionType:
    type: object
    required:
      - dataFormat
    properties:
      dataFormat:
        type: string
        description: >-
          Data format specifies whether the data stream should output the data
          as is or whether it should process the data by a given model. In the
          case of the latter, a modelId is required.
        enum:
          - raw
          - processed
      modelId:
        type: integer
